---
- name: uninstall nslcd
  package:
    name: '{{ item }}'
    state: absent
    purge: yes
  with_items:
    - nslcd
    - nscd
    - unscd

- name: install sssd packages
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - sssd
    - sssd-ldap
    - sssd-tools
